"""
brahma_v6/ops/ten_million/report.py — Generates markdown report from simulation results
Phase 5 | 2026-07-09
"""
from __future__ import annotations
import time
from typing import Dict, List, Optional, Any

from brahma_v6.ops.ten_million.invariant_checker import InvariantChecker, InvariantResult
from brahma_v6.ops.ten_million.optimizer import PolicyScore


def generate_report(
    invariant_checker: InvariantChecker,
    best_policy: Optional[PolicyScore],
    all_scores: List[PolicyScore] = None,
    n_events: int = 10_000_000,
    elapsed_seconds: float = 0.0,
    output_path: str = None,
) -> str:
    """
    Generate a markdown report from invariant check results and optimizer output.
    Returns markdown string and optionally writes to output_path.
    """
    ts = time.strftime("%Y-%m-%d %H:%M:%S UTC", time.gmtime())
    lines = [
        "# 10M Event Simulation Report",
        f"\n**Generated:** {ts}",
        f"**Events simulated:** {n_events:,}",
        f"**Elapsed:** {elapsed_seconds:.2f}s",
        "",
        "---",
        "",
        "## Invariant Check Results",
        "",
        f"**Overall:** {'✅ ALL PASSED' if invariant_checker.all_passed() else '❌ VIOLATIONS FOUND'}",
        f"**Total violations:** {invariant_checker.violation_count()}",
        "",
        "| ID | Description | Checked | Violations | Rate | Status |",
        "|----|----|----|----|----|----|",
    ]

    for inv_id, result in invariant_checker.results.items():
        status = "✅" if result.passed else "❌"
        rate = f"{result.violation_rate:.4%}" if result.checked > 0 else "N/A"
        lines.append(
            f"| {inv_id} | {result.description} | {result.checked:,} | "
            f"{result.violations} | {rate} | {status} |"
        )

    lines += [
        "",
        "---",
        "",
        "## Best Policy (Optimizer)",
        "",
    ]

    if best_policy and best_policy.valid:
        p = best_policy.params
        lines += [
            f"**Composite Score:** {best_policy.composite_score:.4f}",
            f"**Win Rate:** {best_policy.win_rate:.2%}",
            f"**Expectancy:** {best_policy.expectancy:.4f}",
            f"**Risk Score:** {best_policy.risk_score:.4f}",
            "",
            "| Parameter | Value |",
            "|-----------|-------|",
            f"| leverage | {p.leverage} |",
            f"| daily_loss_pct | {p.daily_loss_pct:.1%} |",
            f"| max_trades | {p.max_trades} |",
            f"| min_score | {p.min_score} |",
            f"| stop_loss_pct | {p.stop_loss_pct:.1%} |",
            f"| trailing_activation_pct | {p.trailing_activation_pct:.1%} |",
        ]
    else:
        lines.append("⚠️ No valid policy found (all have invariant violations)")

    if all_scores:
        top5 = [s for s in all_scores[:5] if s.valid]
        if top5:
            lines += [
                "",
                "## Top 5 Valid Policies",
                "",
                "| Rank | Score | Win Rate | Expectancy | Leverage | Min Score |",
                "|------|-------|----------|------------|----------|-----------|",
            ]
            for i, s in enumerate(top5, 1):
                p = s.params
                lines.append(
                    f"| {i} | {s.composite_score:.4f} | {s.win_rate:.2%} | "
                    f"{s.expectancy:.4f} | {p.leverage} | {p.min_score} |"
                )

    lines += ["", "---", "", "_Report auto-generated by Brahma-Quant Full-Auto Live Lite_", ""]

    report = "\n".join(lines)

    if output_path:
        from pathlib import Path
        Path(output_path).parent.mkdir(parents=True, exist_ok=True)
        Path(output_path).write_text(report)

    return report
